pap.pdf: k-order-gene-representation-models.tex
	pdflatex k-order-gene-representation-models.tex
	bibtex k-order-gene-representation-models
	pdflatex k-order-gene-representation-models.tex
	pdflatex k-order-gene-representation-models.tex
